name: Python Lint and Format Check (Ruff)

on:
  push:
    branches: [main]
    paths: ["instagram/**"]
  pull_request:
    branches: [main]
    paths: ["instagram/**"]

permissions:
  contents: read

jobs:
  ruff:
    name: Lint and Format (Ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.4"
          args: check --output-format=github
          # src: "./instagram"

      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.4"
          args: format --check --diff
          # src: "./instagram"
